REFUND_STATUS_PENDING = 'pending'
REFUND_STATUS_APPLIED = 'applied'
REFUND_STATUS_PROCESSING = 'processing'
REFUND_STATUS_SUCCESS = 'success'
REFUND_STATUS_FAILED = 'failed'

SHIP_STATUS_PENDING = 'pending'
SHIP_STATUS_DELIVERED = 'delivered'
SHIP_STATUS_RECEIVED = 'received'