REFUND_STATUS_PENDING = "pending"
REFUND_STATUS_APPLIED = "applied"
REFUND_STATUS_PROCESSING = "processing"
REFUND_STATUS_SUCCESS = "success"
REFUND_STATUS_FAILED = "failed"

SHIP_STATUS_PENDING = "pending"
SHIP_STATUS_DELIVERED = "delivered"
SHIP_STATUS_RECEIVED = "received"

TYPE_FIXED = "fixed"
TYPE_PERCENT = "percent"

PAYMENT_STATUS_WAITING = "waiting"
PAYMENT_STATUS_PREAUTH = "preauth"
PAYMENT_STATUS_CONFIRMED = "confirmed"
PAYMENT_STATUS_REJECTED = "rejected"
PAYMENT_STATUS_REFUNDED = "refunded"

VOUCHER_TYPE_PRODUCT = "product"
VOUCHER_TYPE_CATEGORY = "category"
VOUCHER_TYPE_SHIPPING = "shipping"
VOUCHER_TYPE_VALUE = "value"

ORDER_STATUS_DRAFT = "draft"
ORDER_STATUS_UNFULFILLED = "unfulfilled"
ORDER_STATUS_FULFILLED = "fulfilled"
ORDER_STATUS_CANCELED = "canceled"
